# Generated by Django 5.1.4 on 2025-01-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_team'),
        ('users', '0002_remove_company_created_at_company_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='team',
            name='company',
        ),
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
