# Generated by Django 5.1.4 on 2025-01-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
    ]
